// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/stack-trace/stack-trace.d.ts
declare module 'stack-trace' {
  export interface StackFrame {
    getTypeName():string;
    getFunctionName():string;
    getMethodName():string;
    getFileName():string;
    getTypeName():string;
    getLineNumber():number;
    getColumnNumber():number;
    isNative():boolean;
  }

  export function get(belowFn?:() => void): StackFrame[];
  export function parse(err:Error): StackFrame[];
}
